resources:
- name: Hack-n-Stash
  type: git
  source:
      uri: {{github-uri}}
      branch: {{github-branch}}
      private_key: {{github-private-key}}

- name: keystoneXXL
  type: cf
  source:
    api: api.sys.pcfdev.one.west.com
    username: ((cf_user))
    password: ((cf_password))
    organization: Hackathon
    space: Dev
    skip_cert_check: true

jobs:
- name: test-app
  plan:
  - get: Hack-n-Stash
    trigger: true
  - task: tests
    file: Hack-n-Stash/keystoneXXL-pipeline/ci/tasks/build.yml
  - put: keystoneXXL
    params:
      manifest: Hack-n-Stash/keystoneXXL-pipeline/manifest.yml
